Q =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
R =
 [[-1.41421356e+00  3.33066907e-16]
 [ 0.00000000e+00 -1.41421356e+00]]
Check A = Q @ R:
 True


In [4]:
#----LU----Decomposition----Matrix--------------------------
import numpy as np

# Given Matrix A
A = np.array([
    [2, 3, 1],
    [4, 5, 2],
    [6, 7, 3]
], float)

# Size of the matrix
n = A.shape[0]

# Initialize L and U with zeros
L = np.zeros((n, n))
U = np.zeros((n, n))

# Doolittle's Method
for i in range(n):
    # Upper Triangular Matrix (U)
    for k in range(i, n):
        sum = 0
        for j in range(i):
            sum += L[i][j] * U[j][k]
        U[i][k] = A[i][k] - sum

    # Lower Triangular Matrix (L)
    for k in range(i, n):
        if i == k:
            L[i][i] = 1  # Diagonal element = 1
        else:
            sum = 0
            for j in range(i):
                sum += L[k][j] * U[j][i]
            L[k][i] = (A[k][i] - sum) / U[i][i]

# Print Results
print("Matrix A:")
print(A)
print("\nLower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)

# Verify: L * U = A
print("\nCheck L * U:")
print(np.dot(L, U))


Matrix A:
[[2. 3. 1.]
 [4. 5. 2.]
 [6. 7. 3.]]

Lower Triangular Matrix L:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 2. 1.]]

Upper Triangular Matrix U:
[[ 2.  3.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]

Check L * U:
[[2. 3. 1.]
 [4. 5. 2.]
 [6. 7. 3.]]


In [5]:
#---QR---decomposition----------------
import numpy as np

A = np.array([[1, 1],
              [1, -1]])

Q, R = np.linalg.qr(A)

print("Q =\n", Q)
print("R =\n", R)
print("Check A = Q @ R:\n", np.allclose(A, Q @ R))



Q =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
R =
 [[-1.41421356e+00  3.33066907e-16]
 [ 0.00000000e+00 -1.41421356e+00]]
Check A = Q @ R:
 True


In [6]:
# Python program to find decompose of a
# matrix using Cholesky Decomposition

def choleskyDecomposition(matrix):
    n = len(matrix)

    # to store the lower triangular matrix
    lower = [[0] * n for _ in range(n)]

    # Decomposing a matrix into Lower Triangular
    for i in range(n):
        for j in range(i + 1):
            sum = 0

            # summation for diagonals
            if j == i:
                for k in range(j):
                    sum += lower[j][k]**2
                lower[j][j] = int((matrix[j][j] - sum)**0.5)
            else:

                # Evaluating L(i, j) using L(j, j)
                for k in range(j):
                    sum += lower[i][k] * lower[j][k]
                lower[i][j] = (matrix[i][j] - sum) // lower[j][j]

    # Displaying Lower Triangular Matrix
    for i in range(n):
        print(" ".join(map(str, lower[i])))

    print()

    # Displaying Transpose of Lower Triangular Matrix
    for i in range(n):
        print(" ".join(map(str, [lower[j][i] for j in range(n)])))

if __name__ == "__main__":
    matrix = [
        [4, 12, -16],
        [12, 37, -43],
        [-16, -43, 98]
    ]
    choleskyDecomposition(matrix)

2 0 0
6 1 0
-8 5 3

2 6 -8
0 1 5
0 0 3


In [ ]:
#--------Non-Negative Matrix Factorization (NMF)?------------------

import numpy as np
from sklearn.decomposition import NMF

# Original non-negative matrix
V = np.array([
    [5, 3, 0],
    [4, 0, 0],
    [1, 1, 0],
    [0, 2, 5]
], dtype=float)

# Number of latent features
r = 2

# Create NMF model
model = NMF(n_components=r, init='random', random_state=0)

# Fit the model and get W and H
W = model.fit_transform(V)
H = model.components_

print("Original Matrix V:\n", V)
print("\nMatrix W (users x features):\n", W)
print("\nMatrix H (features x items):\n", H)

# Approximate V from W and H
V_approx = np.dot(W, H)
print("\nReconstructed V (W @ H):\n", V_approx)


Original Matrix V:
 [[5. 3. 0.]
 [4. 0. 0.]
 [1. 1. 0.]
 [0. 2. 5.]]

Matrix W (users x features):
 [[0.21403525 1.20199197]
 [0.         0.78543444]
 [0.12495814 0.2671365 ]
 [3.25365407 0.        ]]

Matrix H (features x items):
 [[0.         0.63598988 1.52786846]
 [4.41565694 1.72909944 0.        ]]

Reconstructed V (W @ H):
 [[5.30758419 2.2144879  0.32701771]
 [3.46820903 1.35809425 0.        ]
 [1.17958316 0.54137769 0.1909196 ]
 [0.         2.06929106 4.97115542]]
